version: '3.8'

services:
  service-cart:
    build:
      context: .
      dockerfile: apps/service-cart/service-cart.Dockerfile
    ports:
      - '9000:9000'

  service-authentification:
    build:
      context: .
      dockerfile: apps/service-authentification/serviceAuthentification.Dockerfile
    ports:
      - '3001:3001'

  # mongodb:
  #   image: mongo:latest
  #   ports:
  #     - '27017:27017'

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: service-cart
