version: '3.8'

services:
  service-cart:
    build:
      context: .
      dockerfile: service-cart.Dockerfile
    ports:
      - '9000:9000'

  service-authentification:
    build:
      context: .
      dockerfile: serviceAuthentification.Dockerfile
    ports:
      - '3001:3001'
